# Generated by Django 4.0 on 2021-12-31 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cars',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mileage', models.IntegerField(default=0)),
                ('year_of_manufacture', models.IntegerField(default=0)),
                ('manufacturer', models.CharField(max_length=50)),
                ('model', models.CharField(max_length=50)),
                ('fuel_efficiency', models.IntegerField(blank=True, default=0)),
            ],
        ),
    ]
